In [1]:
#1. Implement Simple Naïve Bayes classification algorithm using Python/R on iris.csv dataset.

#2. Compute Confusion matrix to find TP, FP, TN, FN, Accuracy, Error rate, 
#Precision, Recall on the given dataset.


In [18]:
import pandas as pd
import numpy as np
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix 
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
import seaborn as sns

In [17]:
df = sns.load_dataset('iris')

In [16]:
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [35]:
# For example, if the dataset has only 5 columns
df_x = df.iloc[:, :4]     # First 4 columns as features
df_y = df.iloc[:, 4]      # 5th column as target


In [39]:
x_train, x_test, y_train, y_test = train_test_split(df_x, df_y, test_size=0.2, random_state=42)
#df_x: your features (independent variables)

#df_y: your target (dependent variable)

#test_size=0.2: 20% of the data will be used for testing, 80% for training

#random_state=42: ensures reproducibility of results

In [41]:
sc = preprocessing.StandardScaler()
x_train = sc.fit_transform(x_train)

In [43]:
GNB = GaussianNB()
GNB.fit(x_train,y_train)

GaussianNB()

In [45]:
y_pred = GNB.predict(x_test)

D:\ADITYA\Anaconda\Lib\site-packages\sklearn\base.py:486: UserWarning: X has feature names, but GaussianNB was fitted without feature names
  warnings.warn(


In [47]:
print(y_pred)

['virginica' 'virginica' 'virginica' 'virginica' 'virginica' 'virginica'
 'virginica' 'virginica' 'virginica' 'virginica' 'virginica' 'virginica'
 'virginica' 'virginica' 'virginica' 'virginica' 'virginica' 'virginica'
 'virginica' 'virginica' 'virginica' 'virginica' 'virginica' 'virginica'
 'virginica' 'virginica' 'virginica' 'virginica' 'virginica' 'virginica']


In [49]:
##################  CONFUSION MATRIX

In [53]:
from sklearn.metrics import confusion_matrix, accuracy_score 
cm= confusion_matrix(y_test,y_pred) 
print('Confusion Matrix: ') 
print(cm) 
ac1 =accuracy_score(y_test, y_pred)*100 
print('Accuracy Score in precentage:') 
print(ac1)

Confusion Matrix: 
[[ 0  0 10]
 [ 0  0  9]
 [ 0  0 11]]
Accuracy Score in precentage:
36.666666666666664


In [57]:
tp=cm[0][0]

fn=(cm[0][1])+(cm[0][2])

tn=(cm[1][1])+(cm[1][2])+(cm[2][1])+(cm[2][2]) 
fp=(cm[1][0])+(cm[2][0])

print('true positive:', tp)

print('false positive:' ,fp)

print('true negative:',tn) 
print('false negative: ',fn)

error_rate=(fp+fn)/(tp+tn+fp+fn) 
print('error rate:', error_rate)


true positive: 0
false positive: 0
true negative: 20
false negative:  10
error rate: 0.3333333333333333


In [59]:
tp=cm[1][1]

fn=(cm[1][0])+(cm[1][2])

tn=(cm[0][0])+(cm[0][2])+(cm[2][0])+(cm[2][2]) 
fp=(cm[0][1])+(cm[2][1])

print('true positive:', tp)

print('false positive:' ,fp)

print('true negative:',tn) 
print('false negative: ',fn)

error_rate=(fp+fn)/(tp+tn+fp+fn) 
print('error rate:', error_rate)

true positive: 0
false positive: 0
true negative: 21
false negative:  9
error rate: 0.3


In [65]:
tp=cm[1][2]

fn=(cm[2][0])+(cm[2][1])

tn=(cm[0][0])+(cm[0][1])+(cm[1][0])+(cm[1][1]) 
fp=(cm[0][2])+(cm[1][2])

print('true positive:', tp)

print('false positive:' ,fp)

print('true negative:',tn) 
print('false negative: ',fn)

error_rate=(fp+fn)/(tp+tn+fp+fn) 
print('error rate:', error_rate)

true positive: 9
false positive: 19
true negative: 0
false negative:  0
error rate: 0.6785714285714286


In [67]:
#####  DISPLAY THE REPORT

In [72]:
from sklearn.metrics import classification_report

In [78]:
print ("Classification Report\n")
print (classification_report(y_test,y_pred))

Classification Report

              precision    recall  f1-score   support

      setosa       0.00      0.00      0.00        10
  versicolor       0.00      0.00      0.00         9
   virginica       0.37      1.00      0.54        11

    accuracy                           0.37        30
   macro avg       0.12      0.33      0.18        30
weighted avg       0.13      0.37      0.20        30



D:\ADITYA\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
D:\ADITYA\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
D:\ADITYA\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [80]:
###########    ERROR RATE FOR COMPLETE SAMPLE

In [82]:
print("Error Rate: ")
print(100-ac1)

Error Rate: 
63.333333333333336


In [84]:
from sklearn.metrics import precision_score, recall_score

In [86]:
prec = precision_score(y_test, y_pred, average = None)

D:\ADITYA\Anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [88]:
prec

array([0.        , 0.        , 0.36666667])

In [90]:
print (prec)

[0.         0.         0.36666667]


In [92]:
rec = recall_score (y_test,y_pred ,average = None)

In [94]:
rec

array([0., 0., 1.])